name: hyperpay
description:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nyartech.hyperpay
        pluginClass: HyperpayPlugin
      ios:
        pluginClass: HyperpayPlugin
